### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#10]
As a **user** I can **register an account** so that **I can access all features of the site**

## Acceptance Criteria
* **Given** that I do not have an account
**When** I visit the landing page
**Then** I have the option to sign up
* **Given** that I do not not have an account and am on the registration page
**When** I enter my details and password and submit it
**Then** an account is created for me

## Tasks
- [x] Create a button or link on the landing page to direct users to the registration page
- [x] Create a registration form
- [x] Create functionality for the user to register an account
