### ISSUE TITLE
USER STORY: Login and logout

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#11]
As a **user** I can **login and logout of my account** so that **I can use the site and keep my account secure**

## Acceptance Criteria
* **Given** that I am a registered user that is not logged in
**When** I navigate to the login page via the login link and enter my details
**Then** I am logged into my account
* **Given** that I am logged in to my account
**When** I click on the option to logout
**Then** I am logged out of my account
* **Given** that I have an account
**When** I am logged in
**Then** I cannot see an option to signup and can see an option to logout

## Tasks
- [x] Create login and logouts buttons
- [x] Create relevant form
- [x] Create functionality for users to login and logout
- [x] Remove the sign-up/log in button or link when the user is logged in and display a logout option
