### ISSUE TITLE
USER STORY: Edit profile

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#16]
As a **user** I can **edit my profile details** so that **I can keep my profile information up to date**

## Acceptance Criteria
* **Given** that I am logged into the site
**When** I view the navbar
**Then** there is a link to my profile
* **Given** that I click on the link to my profile
**When** I view my profile details
**Then** there is an option to edit my profile
* **Given** that I clicked the option to edit my profile
**When** I enter my new details and submit them
**Then** my profile is updated with the new details

## Tasks
- [x] Create a link to the profile page
- [x] Create a page to display the profile information
- [x] Create a link to edit the profile details
- [x] Create functionality to prepopulate a form with old details to edit the profile
- [x] Create functionality to edit the profile with new submitted details
