### ISSUE TITLE
USER STORY: Add a profile avatar

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#17]
As a **user** I can **add an avatar to my profile** so that **my profile can be more personalized**

## Acceptance Criteria
* **Given** that I am logged in and editing my profile
**When** I add an avatar and submit it
**Then** my profile is updated with the new avatar

## Tasks
- [x] Wire up Cloudinary 
- [x] Create functionality for users to upload images
- [x] Create functionality to update user profiles with uploaded avatar images
