### ISSUE TITLE
USER STORY: Change password

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#18]
As a **user** I can **change my password** so that **I can keep my account secure**

## Acceptance Criteria
* **Given** that I am logged in
**When** I view my profile page
**Then**  there is an option to change my password
* **Given** that I click the option to change my password
**When** I enter my new password and submit it via the presented form
**Then**  my password is changed

## Tasks
- [x] Add a link to change a user's password
- [x] Create a form for the user to fill in their new password
- [x] Create functionality to update the user's password with the new one
