### ISSUE TITLE
USER STORY: Delete profile

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#19]
As a **user** I can **delete my profile** so that **I can control whether or not I am a member of the site**

## Acceptance Criteria
* **Given** that I am logged in to the site
**When** I view my profile page
**Then** there is an option to delete my profile
* **Given** that I click the option to delete my profile
**When** I confirm the profile deletion
**Then** my profile is deleted and I am logged out

## Tasks
- [ ] Add a link to delete the user's profile
- [ ] Create a deletion confirmation form
- [ ] Create functionality to delete the users profile
