### ISSUE TITLE
USER STORY: Profile page

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#20]
As a **user** I can **view user profiles** so that **I can find out more information about the relevant user**

## Acceptance Criteria
* **Given** that I am viewing the site
**When** I click on a user's profile link
**Then** I am presented with the relevant profile and information

## Tasks
- [ ] Create a page to display profiles
- [ ] Create links with usernames to direct to relevant profiles
- [ ] Create functionality to display the relevant user profile details
