### ISSUE TITLE
USER STORY: Popular profiles list

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#22]
As a **user** I can **view a list of the most popular profiles** so that **I can see which profiles have the most intriguing content**

## Acceptance Criteria
* **Given** that I am visiting the site
**When** I view any of the main site pages
**Then** I can see a list of popular profiles
* **Given** that I am viewing the popular profile list
**When** I click on any of the profiles
**Then** I am directed to the relevant profile page

## Tasks
- [ ] Add a section for the popular profiles list
- [ ] Create functionality to display the most popular profiles
- [ ] Make the profiles clickable as links that direct to relevant pages

## Epic: #4
