### ISSUE TITLE
USER STORY: Profiles search

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#24]
As a **user** I can **search for specific profiles** so that **I can easily find a profile I am looking for**

## Acceptance Criteria
* **Given** that I am visiting the site
**When** I view any of the main site pages
**Then** I can see a search bar to search for profiles
* **Given** that I have clicked on the search bar
**When** I enter details to search for
**Then** I can see the results of my search

## Tasks
- [ ] Add a search bar
- [ ] Create functionality to get profiles relevant to the search details
- [ ] Create functionality to display the search results to the user
