### ISSUE TITLE
USER STORY: Follow and unfollow users

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#25]
As a **user** I can **follow and unfollow other users** so that **I can control which user's posted photos I see in my feed**

## Acceptance Criteria
* **Given** that I am viewing the popular profiles list
**When** I look at each profile
**Then** there is a button to follow the profile next to their username
* **Given** that I have clicked on a link to a user's profile
**When** I view their profile page
**Then** there is a button to follow the profile
* **Given** that I want to follow a user
**When** I click on the relevant follow button
**Then** the button option changes to unfollow and I am following the user
* **Given** that I am following a user and want to unfollow them
**When** I click on the relevant unfollow button
**Then** the button option changes to follow again and I am no longer following the user

## Tasks
- [x] Add buttons for following/unfollowing
- [x] Create functionality to change button content according to following status
- [x] Create functionality for users to follow and unfollow other users
