### ISSUE TITLE
USER STORY: View user's followers

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#26]
As a **user** I can **view all of a certain user's followers** so that **I find out who follows them**

## Acceptance Criteria
* **Given** that I am viewing a user's profile page
**When** I view their statistics details and click on the followers option
**Then** I am presented with a list of the user's followers

## Tasks
- [ ] Make the followers statistic display clickable
- [ ] Create functionality to get all relevant followers for the user
- [ ] Create functionality to display the list of followers
