### ISSUE TITLE
USER STORY: View user's followed profiles

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#27]
As a **user** I can **view all profiles that a certain user follows** so that **I can find out who they follow**

## Acceptance Criteria
* **Given** that I am viewing a user's profile page
**When** I view their statistics details and click on the "following" option
**Then** I am presented with a list of profiles that the user follows

## Tasks
- [ ] Make the "following" statistic display clickable
- [ ] Create functionality to get all relevant profiles that the user follows
- [ ] Create functionality to display the list of followed profiles
