### ISSUE TITLE
USER STORY: Create a photo post

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#28]
As a **user** I can **post a photo with details** so that **I can share my photographs on the site**

## Acceptance Criteria
* **Given** that I am logged in as a registered user
**When** I view the site
**Then** there is an option for me to post a photo
* **Given** that I am logged in as a registered user
**When** I click on the option to post a photo
**Then** I am presented with a form to enter the photo and details
* **Given** that I have entered the relevant details
**When** I submit the form
**Then** my photo is posted to the site along with associated details

## Tasks
- [x] Add a button option for posting a photo
- [x] Create a form for the user to submit data
- [x] Create functionality to save the details 
- [x] Ensure Cloudinary is linked up properly to store the photo
