### ISSUE TITLE
USER STORY: Edit a posted photo

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#29]
As a **user** I can **edit a photo that I have posted** so that **I can ensure the content is correct and up to date**

## Acceptance Criteria
* **Given** that I am logged in as a registered user
**When** I view my own posted photo
**Then** there is an option for me to edit the photo
* **Given** that I am logged in as a registered user and view my own posted photo
**When** I click the option to edit the photo
**Then** I am presented with a prepopulated form containing the old data
* **Given** that I have clicked the option to edit my photo
**When** I fill in the form to edit my photo and submit it
**Then** the relevant post is updated with the new content

## Tasks
- [ ] Add an option for editing a posted photo
- [ ] Create functionality to prepopulate the edit form with old data
- [ ] Create functionality to update the relevant photo with newly submitted data
