### ISSUE TITLE
USER STORY: Delete a posted photo

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#30]
As a **user** I can **delete a photo that I have posted** so that **I can remove content that I no longer want to share on the site**

## Acceptance Criteria
* **Given** that I am logged in as a registered user
**When** I view my own posted photo
**Then** there is an option for me to delete the photo
* **Given** that I am logged in as a registered user and click the option to delete my posted photo
**When** I confirm the profile deletion
**Then** the photo is deleted and is no longer shown on the site

## Tasks
- [x] Add an option to delete posted photos
- [x] Create a deletion confirmation form
- [x] Create functionality to delete the photo
