### ISSUE TITLE
USER STORY: View followed user's posted photos

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#32]
As a **user** I can **view photos posted by users that I follow** so that **I can view content specific to my taste and follow their activity**

## Acceptance Criteria
* **Given** that I am logged in as a registered user
**When** I view navigation options
**Then** there is an option for me to view my feed
* **Given** that I have followed other users on the site
**When** I navigate to my feed
**Then** only photos posted by users that I follow are displayed

## Tasks
- [x] Add a button for users to use to navigate to their feed
- [x] Create functionality to get photos relevant to users that are followed
- [x] Create functionality to display the posted photos
