### ISSUE TITLE
USER STORY: Posted photos search

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#33]
As a **user** I can **search for specific photos that have been posted** so that **I can easily find content I am looking for**

## Acceptance Criteria
* **Given** that I am visiting the site
**When** I view pages relevant to posted photos
**Then** I can see a search bar to search for specific photos
* **Given** that I have clicked on the search bar
**When** I enter details to search for
**Then**  I can see the results of my search

## Tasks
- [x] Add a search bar
- [x] Create functionality to get photos relevant to the search details
- [x] Create functionality to display the search results to the user
