### ISSUE TITLE
USER STORY: Like and unlike posted photos

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#34]
As a **user** I can **like and unlike other user's posted photos** so that **I can easily show/remove appreciative feedback**

## Acceptance Criteria
* **Given** that I am logged in as a registered user
**When** I view photos that have been posted by other users
**Then**  I can see an option to like the photo
* **Given** that I want to like a certain photo
**When** I click on the like button
**Then**  it is registered that I liked the photo and the number of likes increases
* **Given** that I have liked a photo and want to change my mind
**When** I click on the like button again
**Then**  it is registered that I unliked the photo and the number of likes decreases again

## Tasks
- [ ] Add a button to like photos
- [ ] Add a display to show the number of likes
- [ ] Create functionality to add and removes likes
