### ISSUE TITLE
USER STORY: Comment on photos

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#35]
As a **user** I can **comment on a posted photo** so that **I can provide my feedback**

## Acceptance Criteria
* **Given** that I am logged in as a registered user
**When** I view photos that have been posted
**Then**  I can see an option to comment on the photo
* **Given** that I want to comment on a certain photo
**When** I click on the comment button
**Then**  I am presented with a form to add my own comment
* **Given** that I want to comment on a certain photo
**When** I add my comment to the form and submit it
**Then**  my comment is added to the photo

## Tasks
- [x] Add a button for comments
- [x] Add a form for users to add a comment
- [x] Create functionality to add the comment to the photo when submitted
