### ISSUE TITLE
USER STORY: Edit comments

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#36]
As a **user** I can **edit my own comments** so that **I can ensure the correct content is being shared**

## Acceptance Criteria
* **Given** that I have commented on a photo
**When** I view the comment
**Then**  there is an option to edit it
* **Given** that I want to edit my comment
**When** I click on the option to edit it
**Then**  I am presented with a prepopulated form with the old data
* **Given** that I have clicked the option to edit a comment
**When** I fill in the form and submit it
**Then**  the relevant comment is updated with new details

## Tasks
- [x] Add an option to edit comments
- [x] Create functionality to prepopulate the form with old data
- [x] Create functionality to update the relevant comment with the new data
