### ISSUE TITLE
USER STORY: View comments

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#37]
As a **user** I can **view all comments with their details** so that **I can see details of who has commented and what they have said**

## Acceptance Criteria
* **Given** that I am viewing a posted photo
**When** I click on the comments button
**Then**  I am presented with all the relevant comments for the photo
* **Given** that I am viewing a posted photo
**When** I am viewing comments on the photo
**Then**  I can see details about who the owner is and when they commented

## Tasks
- [x] Create functionality to get all comments relevant to the photo
- [x] Create functionality to display all the relevant comments
- [x] Create functionality to display owners and times of the comments
