### ISSUE TITLE
USER STORY: Delete comments

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#38]
As a **user** I can **delete my own comment** so that **I can remove it from the site if I no longer want to share it**

## Acceptance Criteria
* **Given** that I have commented on a photo
**When** I view my own comment
**Then** there is an option to delete it
* **Given** that I click on the option to delete the comment
**When** I confirm the deletion
**Then** the comment is deleted and is no longer shown on the site

## Tasks
- [x] Add an option to delete comments
- [x] Create a deletion confirmation form
- [x] Create functionality to delete the comment
