### ISSUE TITLE
USER STORY: Create a tour

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#39]
As a **site admin** I can **create and post a tour with details** so that **I can advertise photographic tours on the site**

## Acceptance Criteria
* **Given** that I am logged in as the admin
**When** I view the tour section of the site
**Then** there is an option to add a tour
* **Given** that I am logged in as the admin
**When** I click on the option to add a tour
**Then** I am presented with a form to enter the tour details
* **Given** that I have entered the relevant details
**When** I submit the form
**Then** the new tour is posted to the site along with associated details

## Tasks
- [x] Add a button option for adding a tour
- [x] Create a form for the user to submit data
- [x] Create functionality to save the details
- [x] Ensure Cloudinary is linked up properly to store the photo
