### ISSUE TITLE
USER STORY: Edit a tour

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#40]
As a **site admin** I can **edit a tour** so that **I can ensure the content is correct and up to date**

## Acceptance Criteria
* **Given** that I am logged in as the admin
**When** I view a tour that I posted
**Then** there is an option for me to edit the tour
* **Given** that I am logged in as the admin and want to edit a tour
**When** I click the option to edit the tour
**Then** I am presented with a prepopulated form containing the old data
* **Given** that I have clicked the option to edit a tour
**When** I fill in the form and submit it
**Then** the relevant tour is updated with the new content

## Tasks
- [x] Add an option for editing a tour
- [x] Create functionality to prepopulate the edit form with old data
- [x] Create functionality to update the relevant tour with the newly submitted data
