### ISSUE TITLE
USER STORY: Delete a tour

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#41]
As a **site admin** I can **delete a tour** so that **I can remove content that I no longer want to share on the site**

## Acceptance Criteria
* **Given** that I am logged in as the admin
**When** I view a tour that I posted
**Then** there is an option for me to delete the tour
* **Given** that I am logged in as the admin and click the option to delete the tour
**When** I confirm the deletion
**Then** the tour is deleted and is no longer shown on the site

## Tasks
- [ ] Add an option to delete tours
- [ ] Create a deletion confirmation form
- [ ] Create functionality to delete the tour
