### ISSUE TITLE
USER STORY: View all tours

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#42]
As a **user** I can **view all tours that have been posted on the site** so that **I can browse through tours that might interest me**

## Acceptance Criteria
* **Given** that I am visiting the site
**When** I view the "tours" page
**Then** all tours that have been posted are displayed for me to scroll through

## Tasks
- [x] Add a page for tours
- [x] Create functionality to get all tours that have been posted
- [x] Create functionality to display all of the posted tours on the "tours" page
