### ISSUE TITLE
USER STORY: Indicate tour attendance

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#43]
As a **user** I can **indicate that I am going to attend a tour** so that **I can let others know that I am attending**

## Acceptance Criteria
* **Given** that I am logged in as a registered user
**When** I view tours that have been posted
**Then** I can see an option to mark that I am attending the tour
* **Given** that I want to attend a tour
**When** I click on the option to mark that I'm attending
**Then** the option changes to remove the attending mark, it is registered that I have marked it, and the number of attending users increases
* **Given** that I have marked that I'm attending a tour and I want to change my mind
**When** I click on the option to unmark that I'm attending
**Then** the option changes to "mark as attending" again, it is registered that I have unmarked it and the number of attending users decreases again

## Tasks
- [x] Add a button for users to mark/unmark that they are attending tours
- [x] Add a display to show the number of attending users
- [x] Create functionality to toggle whether a user is attending or not
