### ISSUE TITLE
USER STORY: Tours search

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#44]
As a **user** I can **search for specific tours that have been posted** so that **I can easily find tours that I am looking for**

## Acceptance Criteria
* **Given** that I am visiting the site
**When** I navigate to the "tours" page
**Then** I can see a search bar to search for specific tours
* **Given** that I have clicked on the search bar
**When** I enter details to search for
**Then** I can see the results of my search

## Tasks
- [x] Add a search bar to the "tours" page
- [x] Create functionality to get tours relevant to the search details
- [x] Create functionality to display the search results to the user
