### ISSUE TITLE
USER STORY: View  users attending tours

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#45]
As a **user** I can **view all users that are attending a tour** so that **I can find out who is going on the tour**

## Acceptance Criteria
* **Given** that I am visiting the "tours" page
**When** I view a tour
**Then** there is an option to view the attending users with the number of attending users displayed
* **Given** that I am viewing a tour
**When** I click on the option to view attending users
**Then** I am presented with a list of all users that are attending the tour

## Tasks
- [x] Add a button to view the attending users
- [x] Create functionality to get all users that are attending the tour
- [x] Create functionality to display the list of users
