### ISSUE TITLE
USER STORY: Restrict features to registered users

### ISSUE THREAD

**Issue by Tony118g** [Tony118g/captured#46]
As a **site owner** I want to **restrict certain features to registered users** so that **it encourages people to register to the site and ensures correct functionality**

## Acceptance Criteria
* **Given** that I am an unregistered or logged-out user
**When** I access the site
**Then** I can view basic site content intended for all users
* **Given** that I am an unregistered or logged-out user
**When** I view the navbar
**Then** Only basic links are available to me
* **Given** that I am an unregistered or logged-out user
**When** I access the site
**Then** I cannot perform any actions such as following profiles, liking posts, or commenting
* **Given** that I am an unregistered or logged-out user
**When** I access the site
**Then** I cannot access any content or features that are reserved for logged-in users
* **Given** that I am logged in as a registered user
**When** I access the site
**Then** More navigation options and site features are available to me

## Tasks
- [ ] Create functionality to restrict relevant features to authenticated users
- [ ] Add different content depending on whether a user is authenticated
- [ ] Create prompt messages to ask users to log in to perform certain desired actions
